add_subdirectory(ContactListViewModel)
add_subdirectory(ToolsViewModel)
add_subdirectory(JsonTreeViewModel)
add_subdirectory(NetworkProxyViewModel)
add_subdirectory(ScreenshotViewModel)
add_subdirectory(RecordingViewModel)
add_subdirectory(MiniAppListViewModel)
add_subdirectory(MiniAppRuntimeViewModel)
