add_subdirectory(ContactListViewModel)
add_subdirectory(Base64ToolViewModel)
add_subdirectory(ToolsViewModel)
add_subdirectory(JsonToolViewModel)
add_subdirectory(UuidToolViewModel)
add_subdirectory(NetworkProxyViewModel)
add_subdirectory(ScreenshotViewModel)
add_subdirectory(RecordingViewModel)
add_subdirectory(MiniAppListViewModel)
add_subdirectory(MiniAppRuntimeViewModel)
