# ==============================================================================
# Verify Build Artifact Action
# ==============================================================================
# 
# ç”¨é€”ï¼šéªŒè¯æž„å»ºäº§ç‰©çš„å®Œæ•´æ€§å’Œæ­£ç¡®æ€§
# 
# åŠŸèƒ½ï¼š
#   1. ç»Ÿè®¡åŠ¨æ€åº“ã€é™æ€åº“ã€å¤´æ–‡ä»¶æ•°é‡
#   2. éªŒè¯æ•°é‡æ˜¯å¦ç¬¦åˆé¢„æœŸ
#   3. æ£€æŸ¥å…³é”®æ–‡ä»¶æ˜¯å¦å­˜åœ¨
#   4. è¾“å‡ºè¯¦ç»†çš„éªŒè¯æŠ¥å‘Š
#
# æ”¯æŒå¹³å°ï¼š
#   - windows: .dll / .lib
#   - macos:   .dylib / .a
#   - ios:     .a / .xcframework
#   - android: .so / .a
#   - linux:   .so / .a
#
# ==============================================================================

name: 'Verify Build Artifact'
description: 'Verify that build artifacts are complete and correctly structured'

inputs:
  artifact-path:
    description: 'Root path to the artifact directory'
    required: true
  platform:
    description: 'Target platform (windows/macos/ios/android/linux)'
    required: true
  library-name:
    description: 'Name of the library being built'
    required: true
  expect-shared-libs:
    description: 'Expected minimum number of shared libraries (.dll/.dylib/.so)'
    required: false
    default: '0'
  expect-static-libs:
    description: 'Expected minimum number of static libraries (.lib/.a)'
    required: false
    default: '0'
  expect-headers:
    description: 'Whether to expect header files (true/false)'
    required: false
    default: 'true'

# è¾“å‡ºå˜é‡ï¼Œå¯ä¾›åŽç»­æ­¥éª¤ä½¿ç”¨
outputs:
  shared-lib-count:
    description: 'Number of shared libraries found'
    value: ${{ steps.verify.outputs.shared_count }}
  static-lib-count:
    description: 'Number of static libraries found'
    value: ${{ steps.verify.outputs.static_count }}
  header-count:
    description: 'Number of header files found'
    value: ${{ steps.verify.outputs.header_count }}
  has-warnings:
    description: 'Whether any warnings were raised (true/false)'
    value: ${{ steps.verify.outputs.has_warnings }}

runs:
  using: 'composite'
  steps:
    - name: Verify artifact structure
      id: verify
      shell: bash
      run: |
        # ==================================================================
        # åˆå§‹åŒ–å‚æ•°
        # ==================================================================
        ARTIFACT_PATH="${{ inputs.artifact-path }}"
        PLATFORM="${{ inputs.platform }}"
        LIBRARY="${{ inputs.library-name }}"
        EXPECT_SHARED="${{ inputs.expect-shared-libs }}"
        EXPECT_STATIC="${{ inputs.expect-static-libs }}"
        EXPECT_HEADERS="${{ inputs.expect-headers }}"
        
        echo "::group::ðŸ“¦ Verifying $LIBRARY artifact for $PLATFORM"
        
        HAS_WARNINGS=false
        
        # ==================================================================
        # æ£€æŸ¥ artifact ç›®å½•æ˜¯å¦å­˜åœ¨
        # ==================================================================
        if [ ! -d "$ARTIFACT_PATH" ]; then
          echo "::error::Artifact path does not exist: $ARTIFACT_PATH"
          echo "has_warnings=true" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        cd "$ARTIFACT_PATH"
        
        # ==================================================================
        # æ ¹æ®å¹³å°ç»Ÿè®¡ä¸åŒç±»åž‹çš„æ–‡ä»¶æ•°é‡
        # ==================================================================
        SHARED_COUNT=0
        STATIC_COUNT=0
        HEADER_COUNT=0
        XCFRAMEWORK_COUNT=0
        
        case "$PLATFORM" in
          windows)
            # Windows: .dll (åŠ¨æ€åº“), .lib (å¯¼å…¥åº“/é™æ€åº“)
            SHARED_COUNT=$(find . -name "*.dll" -type f 2>/dev/null | wc -l)
            STATIC_COUNT=$(find . -name "*.lib" -type f 2>/dev/null | wc -l)
            SHARED_EXT="dll"
            STATIC_EXT="lib"
            ;;
          macos)
            # macOS: .dylib (åŠ¨æ€åº“), .a (é™æ€åº“)
            # æ³¨æ„ï¼šä½¿ç”¨ ! -type l æŽ’é™¤ç¬¦å·é“¾æŽ¥ï¼Œé¿å…é‡å¤è®¡æ•°
            SHARED_COUNT=$(find . -name "*.dylib" -type f ! -type l 2>/dev/null | wc -l)
            STATIC_COUNT=$(find . -name "*.a" -type f 2>/dev/null | wc -l)
            SHARED_EXT="dylib"
            STATIC_EXT="a"
            ;;
          ios)
            # iOS: åªä½¿ç”¨é™æ€åº“ï¼Œæ‰“åŒ…åœ¨ XCFramework ä¸­
            SHARED_COUNT=0
            STATIC_COUNT=$(find . -name "*.a" -type f 2>/dev/null | wc -l)
            XCFRAMEWORK_COUNT=$(find . -name "*.xcframework" -type d 2>/dev/null | wc -l)
            SHARED_EXT="(none)"
            STATIC_EXT="a"
            ;;
          android)
            # Android: .so (åŠ¨æ€åº“), .a (é™æ€åº“)
            SHARED_COUNT=$(find . -name "*.so" -type f ! -type l 2>/dev/null | wc -l)
            STATIC_COUNT=$(find . -name "*.a" -type f 2>/dev/null | wc -l)
            SHARED_EXT="so"
            STATIC_EXT="a"
            ;;
          linux)
            # Linux: .so å’Œ .so.* (åŠ¨æ€åº“), .a (é™æ€åº“)
            # éœ€è¦åŒ¹é…ç‰ˆæœ¬å·åŽç¼€ï¼Œå¦‚ libssl.so.3
            SHARED_COUNT=$(find . \( -name "*.so" -o -name "*.so.*" \) -type f ! -type l 2>/dev/null | wc -l)
            STATIC_COUNT=$(find . -name "*.a" -type f 2>/dev/null | wc -l)
            SHARED_EXT="so"
            STATIC_EXT="a"
            ;;
          *)
            echo "::warning::Unknown platform: $PLATFORM"
            ;;
        esac
        
        # ç»Ÿè®¡å¤´æ–‡ä»¶æ•°é‡ (.h å’Œ .hpp)
        HEADER_COUNT=$(find . \( -name "*.h" -o -name "*.hpp" \) -type f 2>/dev/null | wc -l)
        
        # ==================================================================
        # è¾“å‡ºæ–‡ä»¶æ¸…å•
        # ==================================================================
        echo ""
        echo "=== ðŸ“Š File Inventory ==="
        echo "  ðŸ“š Shared libraries (.$SHARED_EXT): $SHARED_COUNT"
        echo "  ðŸ“¦ Static libraries (.$STATIC_EXT): $STATIC_COUNT"
        echo "  ðŸ“„ Header files (.h/.hpp): $HEADER_COUNT"
        
        if [ "$PLATFORM" = "ios" ]; then
          echo "  ðŸ“± XCFrameworks: $XCFRAMEWORK_COUNT"
        fi
        
        # ==================================================================
        # éªŒè¯æ£€æŸ¥
        # ==================================================================
        echo ""
        echo "=== âœ”ï¸ Validation Checks ==="
        
        # --- æ£€æŸ¥åŠ¨æ€åº“æ•°é‡ ---
        if [ "$EXPECT_SHARED" -gt 0 ] && [ "$SHARED_COUNT" -lt "$EXPECT_SHARED" ]; then
          echo "::warning::Expected at least $EXPECT_SHARED shared libraries, found $SHARED_COUNT"
          HAS_WARNINGS=true
        elif [ "$SHARED_COUNT" -gt 0 ]; then
          echo "  âœ… Shared libraries: $SHARED_COUNT (expected >= $EXPECT_SHARED)"
        elif [ "$EXPECT_SHARED" -eq 0 ]; then
          echo "  â„¹ï¸ Shared libraries: $SHARED_COUNT (not required)"
        fi
        
        # --- æ£€æŸ¥é™æ€åº“æ•°é‡ ---
        if [ "$EXPECT_STATIC" -gt 0 ] && [ "$STATIC_COUNT" -lt "$EXPECT_STATIC" ]; then
          echo "::warning::Expected at least $EXPECT_STATIC static libraries, found $STATIC_COUNT"
          HAS_WARNINGS=true
        elif [ "$STATIC_COUNT" -gt 0 ]; then
          echo "  âœ… Static libraries: $STATIC_COUNT (expected >= $EXPECT_STATIC)"
        elif [ "$EXPECT_STATIC" -eq 0 ]; then
          echo "  â„¹ï¸ Static libraries: $STATIC_COUNT (not required)"
        fi
        
        # --- æ£€æŸ¥å¤´æ–‡ä»¶ ---
        if [ "$EXPECT_HEADERS" = "true" ] && [ "$HEADER_COUNT" -eq 0 ]; then
          echo "::warning::No header files found in artifact"
          HAS_WARNINGS=true
        elif [ "$HEADER_COUNT" -gt 0 ]; then
          echo "  âœ… Header files: $HEADER_COUNT"
        fi
        
        # --- iOS XCFramework æ£€æŸ¥ ---
        if [ "$PLATFORM" = "ios" ] && [ "$XCFRAMEWORK_COUNT" -eq 0 ]; then
          echo "::warning::No XCFramework found for iOS build"
          HAS_WARNINGS=true
        elif [ "$PLATFORM" = "ios" ]; then
          echo "  âœ… XCFramework: found"
        fi
        
        # --- å…³é”®æ£€æŸ¥ï¼šæ²¡æœ‰ä»»ä½•åº“æ–‡ä»¶ ---
        if [ "$SHARED_COUNT" -eq 0 ] && [ "$STATIC_COUNT" -eq 0 ]; then
          echo "::warning::No library files found! Build may have failed silently."
          HAS_WARNINGS=true
        fi
        
        # ==================================================================
        # åˆ—å‡ºåº“æ–‡ä»¶ï¼ˆæœ€å¤šæ˜¾ç¤º 20 ä¸ªï¼‰
        # ==================================================================
        echo ""
        echo "=== ðŸ“ Library Files ==="
        find . -type f \( -name "*.dll" -o -name "*.lib" -o -name "*.dylib" -o -name "*.so" -o -name "*.so.*" -o -name "*.a" \) 2>/dev/null | sort | head -20
        
        LIB_TOTAL=$(find . -type f \( -name "*.dll" -o -name "*.lib" -o -name "*.dylib" -o -name "*.so" -o -name "*.so.*" -o -name "*.a" \) 2>/dev/null | wc -l)
        if [ "$LIB_TOTAL" -gt 20 ]; then
          echo "  ... and $((LIB_TOTAL - 20)) more"
        fi
        
        # ==================================================================
        # æ€»è®¡
        # ==================================================================
        TOTAL_FILES=$(find . -type f | wc -l)
        echo ""
        echo "=== ðŸ“ˆ Summary ==="
        echo "  Total files: $TOTAL_FILES"
        
        if [ "$HAS_WARNINGS" = "true" ]; then
          echo ""
          echo "  âš ï¸ Verification completed with warnings"
        else
          echo ""
          echo "  âœ… Verification passed - all checks OK"
        fi
        
        echo "::endgroup::"
        
        # ==================================================================
        # è®¾ç½®è¾“å‡ºå˜é‡ä¾›åŽç»­æ­¥éª¤ä½¿ç”¨
        # ==================================================================
        echo "shared_count=$SHARED_COUNT" >> $GITHUB_OUTPUT
        echo "static_count=$STATIC_COUNT" >> $GITHUB_OUTPUT
        echo "header_count=$HEADER_COUNT" >> $GITHUB_OUTPUT
        echo "has_warnings=$HAS_WARNINGS" >> $GITHUB_OUTPUT
