add_subdirectory(MainWindowSuiteViewModel)
add_subdirectory(PageViewModels)
add_subdirectory(AppUIViewModel)
add_subdirectory(ClientInfoViewModel)
add_subdirectory(UpgradeViewModel)
add_subdirectory(MediaCameraViewModel)
add_subdirectory(CameraDirectoryViewModel)
add_subdirectory(InvocationViewModel)
