name: 'Fix macOS RPATH'
description: 'Fix dylib install names and dependencies to use @rpath for portable deployment'

inputs:
  lib-path:
    description: 'Path to directory containing dylib files'
    required: true
  bin-path:
    description: 'Path to directory containing executable files (optional)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Fix dylib install names and dependencies
      shell: bash
      run: |
        LIB_PATH="${{ inputs.lib-path }}"
        BIN_PATH="${{ inputs.bin-path }}"
        
        echo "::group::Fixing dylib install names in $LIB_PATH"
        
        if [ ! -d "$LIB_PATH" ]; then
          echo "::warning::Library path does not exist: $LIB_PATH"
          exit 0
        fi
        
        cd "$LIB_PATH"
        
        FIXED_COUNT=0
        ERROR_COUNT=0
        
        for f in *.dylib; do
          if [ -f "$f" ] && [ ! -L "$f" ]; then
            echo "Processing: $f"
            
            # Fix the library's own install name
            if install_name_tool -id "@rpath/$f" "$f" 2>&1; then
              FIXED_COUNT=$((FIXED_COUNT + 1))
            else
              echo "::warning::Failed to fix install name for $f"
              ERROR_COUNT=$((ERROR_COUNT + 1))
            fi
            
            # Fix dependencies that reference absolute CI runner paths
            otool -L "$f" 2>/dev/null | tail -n +2 | awk '{print $1}' | while read dep; do
              case "$dep" in
                /Users/runner/*|/home/runner/*|/opt/*)
                  dep_basename=$(basename "$dep")
                  echo "  Fixing dependency: $dep -> @rpath/$dep_basename"
                  install_name_tool -change "$dep" "@rpath/$dep_basename" "$f" 2>&1 || \
                    echo "::warning::Failed to fix dependency $dep in $f"
                  ;;
              esac
            done
          fi
        done
        
        echo "✅ Fixed: $FIXED_COUNT files, ⚠️ Errors: $ERROR_COUNT"
        echo "::endgroup::"
        
        # Fix binary RPATH if bin-path is provided
        if [ -n "$BIN_PATH" ] && [ -d "$BIN_PATH" ]; then
          echo "::group::Fixing binary RPATH in $BIN_PATH"
          cd "$BIN_PATH"
          
          for f in *; do
            if [ -f "$f" ] && [ -x "$f" ] && [ ! -L "$f" ]; then
              echo "Processing binary: $f"
              
              # Add rpath to find libraries
              install_name_tool -add_rpath "@executable_path/../lib" "$f" 2>/dev/null || true
              
              # Fix dependencies
              otool -L "$f" 2>/dev/null | tail -n +2 | awk '{print $1}' | while read dep; do
                case "$dep" in
                  /Users/runner/*|/home/runner/*|/opt/*)
                    dep_basename=$(basename "$dep")
                    echo "  Fixing dependency: $dep -> @rpath/$dep_basename"
                    install_name_tool -change "$dep" "@rpath/$dep_basename" "$f" 2>&1 || \
                      echo "::warning::Failed to fix dependency $dep in $f"
                    ;;
                esac
              done
            fi
          done
          
          echo "::endgroup::"
        fi

    - name: Verify fixes
      shell: bash
      run: |
        LIB_PATH="${{ inputs.lib-path }}"
        
        echo "::group::Verifying dylib dependencies"
        
        if [ -d "$LIB_PATH" ]; then
          cd "$LIB_PATH"
          
          HAS_ABS_PATH=false
          for f in *.dylib; do
            if [ -f "$f" ] && [ ! -L "$f" ]; then
              echo "--- $f ---"
              DEPS=$(otool -L "$f" 2>/dev/null | tail -n +2 | awk '{print $1}')
              echo "$DEPS" | head -6
              
              # Check for remaining absolute CI paths
              if echo "$DEPS" | grep -qE "^(/Users/runner|/home/runner|/opt/)"; then
                echo "::warning::$f still has absolute CI paths in dependencies"
                HAS_ABS_PATH=true
              fi
            fi
          done
          
          if [ "$HAS_ABS_PATH" = "false" ]; then
            echo "✅ All dylib dependencies are properly fixed"
          fi
        fi
        
        echo "::endgroup::"
