include (LinkTargetIncludeDirectories)
include (BuildInstallModule)
function(BuildInterface)
    message(STATUS "====Start Build Interface====")
    set(options)
    set(oneValueArg MODULE_NAME)
    set(multiValueArgs 
    TARGET_SOURCE_HEADER_BASE_DIR TARGET_SOURCE_PUBLIC_HEADER
    TARGET_INCLUDE_DIRECTORIES_BUILD_INTERFACE 
                       TARGET_INCLUDE_DIRECTORIES_INSTALL_INTERFACE 
                       INSTALL_PUBLIC_HEADER TARGET_PUBLIC_HEADER_DIR TARGET_DEPENDENICES_PUBLIC)
    cmake_parse_arguments(INTERFACE "${options}" "${oneValueArg}" "${multiValueArgs}" ${ARGN})

    message(STATUS "Parse Args Results:")
    message(STATUS "MODULE_NAME: ${INTERFACE_MODULE_NAME}")
    message(STATUS "TARGET_INCLUDE_DIRECTORIES_BUILD_INTERFACE: ${INTERFACE_TARGET_INCLUDE_DIRECTORIES_BUILD_INTERFACE}")
    message(STATUS "TARGET_INCLUDE_DIRECTORIES_INSTALL_INTERFACE: ${INTERFACE_TARGET_INCLUDE_DIRECTORIES_INSTALL_INTERFACE}")
    message(STATUS "INSTALL_PUBLIC_HEADER: ${INTERFACE_INSTALL_PUBLIC_HEADER}")
    message(STATUS "TARGET_PUBLIC_HEADER_DIR: ${INTERFACE_TARGET_PUBLIC_HEADER_DIR}")
    message(STATUS "TARGET_DEPENDENICES_PUBLIC: ${INTERFACE_TARGET_DEPENDENICES_PUBLIC}")

    add_library(${INTERFACE_MODULE_NAME} INTERFACE)
    target_sources(${INTERFACE_MODULE_NAME}
            PUBLIC FILE_SET HEADERS 
            BASE_DIRS ${MODULE_TARGET_SOURCE_HEADER_BASE_DIR}
            FILES ${MODULE_TARGET_SOURCE_PUBLIC_HEADER}
        )

    if (DEFINED INTERFACE_TARGET_DEPENDENICES_PUBLIC)
    message(STATUS "will add public link to ${INTERFACE_MODULE_NAME}, link librarys: ${INTERFACE_TARGET_DEPENDENICES_PUBLIC}")
    target_link_libraries(${INTERFACE_MODULE_NAME} INTERFACE ${INTERFACE_TARGET_DEPENDENICES_PUBLIC})
endif()

    LinkTargetIncludeDirectories(
        INTERFACE
        MODULE_NAME ${INTERFACE_MODULE_NAME}
        TARGET_INCLUDE_DIRECTORIES_BUILD_INTERFACE ${INTERFACE_TARGET_INCLUDE_DIRECTORIES_BUILD_INTERFACE}
        TARGET_INCLUDE_DIRECTORIES_INSTALL_INTERFACE ${INTERFACE_TARGET_INCLUDE_DIRECTORIES_INSTALL_INTERFACE}
    )
    
    BuildInstallModule(
            MODULE_NAME ${INTERFACE_MODULE_NAME}
            # TARGET_PUBLIC_HEADER ${INTERFACE_INSTALL_PUBLIC_HEADER}
            # TARGET_PUBLIC_HEADER_DIR ${INTERFACE_INSTALL_PUBLIC_HEADER_DIR}
    )
    message(STATUS "====Finish Build Interface: ${INTERFACE_MODULE_NAME}====")
endfunction()