# 获取传入变量
file(READ "${INPUT_TEMPLATE_FILE}" TEMPLATE_H)
# file(READ "${CMAKE_SOURCE_DIR}/version/templates/version.rc.in" TEMPLATE_RC)

string(TIMESTAMP BUILD_TIME "%Y-%m-%dT%H:%M:%SZ" UTC)
string(REPLACE "@PROJECT_VERSION_MAJOR@" "${MAJOR}" TEMPLATE_H "${TEMPLATE_H}")
string(REPLACE "@PROJECT_VERSION_MINOR@" "${MINOR}" TEMPLATE_H "${TEMPLATE_H}")
string(REPLACE "@PROJECT_VERSION_PATCH@" "${PATCH}" TEMPLATE_H "${TEMPLATE_H}")
string(REPLACE "@GIT_COMMIT_HASH@" "${GIT_HASH}" TEMPLATE_H "${TEMPLATE_H}")
string(REPLACE "@GIT_CURRENT_BRANCH@" "${GIT_BRANCH}" TEMPLATE_H "${TEMPLATE_H}")
string(REPLACE "@PROJECT_COMPILE_TIME@" "${BUILD_TIME}" TEMPLATE_H "${TEMPLATE_H}")
# string(REPLACE "@version_h_file@" "${OUTPUT_H}" TEMPLATE_RC "${TEMPLATE_RC}")

file(WRITE "${OUTPUT_H}" "${TEMPLATE_H}")
# file(WRITE "${OUTPUT_RC}" "${TEMPLATE_RC}")
