#!/usr/bin/env python3
"""
Generate upgrade-manifest.json from per-platform build artifacts.

Usage:
    python generate_upgrade_manifest.py \
        --artifacts-dir ./artifacts \
        --base-url https://github.com/owner/repo/releases/download/v2026.04.0 \
        --release-config ./product/bundle_pack/release-config.json \
        --output ./artifacts/upgrade-manifest.json \
        [--mandatory] \
        [--release-notes "text or empty"]

Inputs:
    - Per-platform package-info.json (generated by CMake at build time):
        { "version": "2026.04.0.1523", "platform": "windows-x64" }
    - Per-platform .sha256 files (generated by CI)
    - release-config.json (product/bundle_pack/):
        { "upgrade": { "minVersion": "...", "mandatory": false } }

Output:
    upgrade-manifest.json uploaded alongside release assets.
"""

import argparse
import glob
import hashlib
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path


def find_primary_package(artifacts_dir: str, label: str) -> Path | None:
    """Find the primary package file for a platform by matching the label in the filename.

    Package names follow: ProductName-Version-<Label>.ext
    e.g. Template-Factory-2026.04.0.606-Windows.zip
    """
    for ext in ("*.zip", "*.dmg", "*.tar.gz"):
        matches = [
            p for p in Path(artifacts_dir).glob(ext)
            if not p.name.endswith(".sha256") and label in p.name
        ]
        if matches:
            return matches[0]
    return None


# Map CI platform labels (from artifact filename) to upgrade manifest keys
PLATFORM_LABEL_TO_KEY = {
    "Windows": "windows-x64",
    "Linux":   "linux-x64",
    "macOS":   "macos-arm64",
}


def read_sha256(package_path: Path) -> str:
    """Read SHA-256 from companion .sha256 file, or compute it."""
    sha_file = Path(str(package_path) + ".sha256")
    if sha_file.exists():
        return sha_file.read_text().strip().split()[0]

    # Fallback: compute from file
    h = hashlib.sha256()
    with open(package_path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    parser = argparse.ArgumentParser(description="Generate upgrade-manifest.json")
    parser.add_argument("--artifacts-dir", required=True,
                        help="Directory containing downloaded build artifacts")
    parser.add_argument("--base-url", required=True,
                        help="Base download URL for release assets")
    parser.add_argument("--release-config", default="product/bundle_pack/release-config.json",
                        help="Path to release-config.json")
    parser.add_argument("--output", required=True,
                        help="Output path for upgrade-manifest.json")
    parser.add_argument("--mandatory", action="store_true",
                        help="Override: force mandatory upgrade")
    parser.add_argument("--release-notes", default="",
                        help="Release notes text (empty = filled later by GitHub)")
    args = parser.parse_args()

    artifacts_dir = Path(args.artifacts_dir)

    # ── Read release-config.json ──
    release_config = {"upgrade": {"minVersion": "", "mandatory": False}}
    config_path = Path(args.release_config)
    if config_path.exists():
        with open(config_path) as f:
            release_config = json.load(f)
        print(f"  Read release config from {config_path}")
    else:
        print(f"  Warning: {config_path} not found, using defaults")

    upgrade_cfg = release_config.get("upgrade", {})
    min_version = upgrade_cfg.get("minVersion", "")
    mandatory = args.mandatory or upgrade_cfg.get("mandatory", False)

    # ── Collect per-platform package-info-*.json files ──
    info_files = list(artifacts_dir.rglob("package-info-*.json"))
    if not info_files:
        # Fallback: try old name for backward compatibility
        info_files = list(artifacts_dir.rglob("package-info.json"))
    if not info_files:
        print("Error: No package-info-*.json files found in", artifacts_dir)
        sys.exit(1)

    version = None
    packages = {}

    for info_file in info_files:
        with open(info_file) as f:
            info = json.load(f)

        pkg_version = info["version"]

        # Derive platform key from filename: package-info-Windows.json → "Windows"
        label = info_file.stem.replace("package-info-", "") or info_file.parent.name
        platform_key = PLATFORM_LABEL_TO_KEY.get(label, label.lower())

        if version is None:
            version = pkg_version
        elif version != pkg_version:
            print(f"  Warning: version mismatch {version} vs {pkg_version} for {platform_key}")

        # Find primary package file by matching platform label in filename
        pkg_path = find_primary_package(info_file.parent, label)
        if pkg_path is None:
            # Try artifacts root (merge-multiple flattens)
            pkg_path = find_primary_package(artifacts_dir, label)

        if pkg_path is None:
            print(f"  Warning: no package file found for {platform_key}, skipping")
            continue

        sha256 = read_sha256(pkg_path)
        size = pkg_path.stat().st_size
        filename = pkg_path.name

        packages[platform_key] = {
            "url": f"{args.base_url}/{filename}",
            "sha256": sha256,
            "size": size,
        }

        print(f"  {platform_key}: {filename} ({size} bytes, sha256={sha256[:16]}...)")

    if not packages:
        print("Error: No packages collected")
        sys.exit(1)

    # ── Assemble manifest ──
    manifest = {
        "version": version,
        "releaseDate": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "releaseNotes": args.release_notes,
        "mandatory": mandatory,
        "minVersion": min_version,
        "packages": packages,
    }

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(manifest, f, indent=2)

    print(f"\n  Generated {output_path}")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
