#pragma once

#include <memory>
#include <string>
#include <vector>

#include <ucf/Utilities/NotificationHelper/INotificationHelper.h>
#include <ucf/Services/ServiceDeclaration/IService.h>
#include <ucf/Services/CameraDirectoryService/ICameraDirectoryServiceCallback.h>

namespace ucf::framework {
    class ICoreFramework;
    using ICoreFrameworkWPtr = std::weak_ptr<ICoreFramework>;
}

namespace ucf::service {

class SERVICE_EXPORT ICameraDirectoryService
    : public IService
    , public virtual ucf::utilities::INotificationHelper<ICameraDirectoryServiceCallback>
{
public:
    ICameraDirectoryService() = default;
    ICameraDirectoryService(const ICameraDirectoryService&) = delete;
    ICameraDirectoryService(ICameraDirectoryService&&) = delete;
    ICameraDirectoryService& operator=(const ICameraDirectoryService&) = delete;
    ICameraDirectoryService& operator=(ICameraDirectoryService&&) = delete;
    virtual ~ICameraDirectoryService() = default;

public:
    // ===== Read =====
    [[nodiscard]] virtual model::CameraGroupArray  getCameraGroups()  const = 0;
    [[nodiscard]] virtual model::CameraEntryArray  getCameras()       const = 0;
    [[nodiscard]] virtual model::CameraDirectoryRelationArray getCameraRelations() const = 0;

    [[nodiscard]] virtual model::ICameraGroupPtr getCameraGroup(const std::string& nodeId) const = 0;
    [[nodiscard]] virtual model::ICameraEntryPtr getCamera(const std::string& nodeId) const = 0;

    // ===== Batch write: caller supplies arrays of interface implementations (id generated by caller) =====
    virtual void addCameraGroups(const model::CameraGroupArray& groups) = 0;
    virtual void updateCameraGroups(const model::CameraGroupArray& groups) = 0;
    virtual void removeCameraGroups(const std::vector<std::string>& nodeIds) = 0;

    virtual void addCameras(const model::CameraEntryArray& cameras) = 0;
    virtual void updateCameras(const model::CameraEntryArray& cameras) = 0;
    virtual void removeCameras(const std::vector<std::string>& nodeIds) = 0;

    virtual void addCameraRelations(const model::CameraDirectoryRelationArray& relations) = 0;
    virtual void updateCameraRelations(const model::CameraDirectoryRelationArray& relations) = 0;
    virtual void removeCameraRelations(const std::vector<std::string>& relationIds) = 0;

    // ===== Lifecycle =====
    // Explicitly trigger "load camera directory data from the database".
    //   - Must be called after DataWarehouseService has reported the database as bound;
    //     otherwise the call is ignored and a log line is emitted.
    //   - Idempotent: subsequent calls while in Loading / Ready state are no-ops;
    //     in Failed state the call retries.
    //   - On completion fires ICameraDirectoryServiceCallback::onCameraDirectoryReady;
    //     on failure fires onCameraDirectoryLoadFailed.
    virtual void loadCameraDirectory() = 0;

    // True after loadCameraDirectory has completed successfully at least once and the in-memory
    // view reflects the database. Lets late-joining subscribers (which missed the
    // onCameraDirectoryReady notification) decide whether to perform an initial sync read
    // instead of waiting for a callback that will never fire again.
    [[nodiscard]] virtual bool isCameraDirectoryReady() const = 0;

public:
    static std::shared_ptr<ICameraDirectoryService> createInstance(ucf::framework::ICoreFrameworkWPtr coreFramework);
};

} // namespace ucf::service
